config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: { registrations: 'registrations' }
  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    delete 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :items
  resources :users, only: [:show]
  root to: "items#index"
 # root to: "home#index"

  resources :friendships

  get "/searches/", to: "searches#index",  as: 'search_results'



  resources :searches do
    resources :items
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  validates_presence_of :friend_id, :user_id

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :search

  def self.friends_items(user)
    Item.where(user_id: user.friend_ids[params: :friend_id])
  end



  def get_etsy_id
    string = self.etsy_url
    regex = /\d+/ #regular expression for finding integers
    numbers = string.scan(regex)
    self[:etsy_id] = numbers[0] #first number in array is the id
  end

  def set_attributes_from_etsy
    etsy_data = get_etsy_data
    listing = etsy_data["results"][0]
    self[:name] = listing["title"].truncate(240)
    self[:description] = listing["description"].truncate(240)
  end

  def get_etsy_data
    HTTParty.get("https://openapi.etsy.com/v2/listings/#{self.etsy_id}?api_key=#{Rails.application.secrets.etsy_api_key}")
  end


end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  has_many :items

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :items

  has_many :friendships, {dependent: :destroy}
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  def not_friends
    # User.all - self.friends - [self]
    already_friends_ids = self.friend_ids
    User.all.reject do |user|
      already_friends_ids.include?(user.id) || self.id == user.id
    end
  end

  # def friends_ids
  #   friend_ids = []
  #   friend_ids << self.friend_ids
  # end

  # def friends_items
  #   @items.where(friends_ids)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 before_action :configure_permitted_paramters, if: :devise_controller?

 protected
  def configure_permitted_paramters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name

  end
   protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user.not_friends
    @friendship = @user.friends
  end

  def show
    @friendships = Friendship.find(params[:id])
  end

  def create
    friend = User.find(params[:friendship][:friend_id])
    current_user.friends << friend
    redirect_to root_path
  end

  def destroy
    @friendship = Friendship.find(params[:id]).destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
    @item = Item.new
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @items = current_user.items.order("created_at DESC") if current_user
  end

  def friends_items
    @friends_items = Item.friends_items(current_user)
    render 'index'
  end

  def show
  end

  def new
    @item = current_user.items.build
  end

  def edit
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to root_path
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end


  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def find_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:title, :description, :image_url, :url)
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :current_password, :password, :password_confirmation)
  end

end

app/controllers/searches_controller.rb
#etsy search controller
class SearchesController < ApplicationController

  def new
    #new search should show all the listings of all categories
    url = "https://openapi.etsy.com/v2/taxonomy/categories?api_key=mi7mse8bmftparcsqwsyassi"
    response = HTTParty.get(url)
    categories = JSON.parse(response.body)
    @cat_list = categories["results"]
    render "new"
  end

  def index
    url = "https://openapi.etsy.com/v2/taxonomy/categories?api_key=mi7mse8bmftparcsqwsyassi"
    response = HTTParty.get(url)
    categories = JSON.parse(response.body)
    @cat_list = categories["results"]

    category = params['name']
    @category = category
    listing_url = "https://openapi.etsy.com/v2/private/listings/active?sort_on=created&sort_order=down&category=#{category}&api_key=mi7mse8bmftparcsqwsyassi&includes=MainImage&limit=100"
    listing_response = HTTParty.get(listing_url)
    @found_products = listing_response['results']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/friendships/index.html.erb
<div class="addfriend">
  <h2>Add Friends</h2>
  <%= form_for @friendship do |f| %>
  <div class="field">
   <%= f.label 'Users of Holiday Wishlist' %> <br>
   <%= f.collection_select :friend_id, @users, :id, :email %>
 </div>
 <div class="actions">
   <%= f.submit 'Add Friend' %>
 </div>
 <% end %>
</div>

app/views/friendships/show.html.erb
<div class="row">
   <div class="col-lg-5 col-xs-12 showfriends">
    <h2>My Friends</h2>
      <ul>
        <% @friendships.each do |friend| %>
        <%= friend.name %>, <%= friend.email %>
        <li>
          (<%= link_to "remove", friendship_path, :method => :delete %>)
          (<%= link_to "Show Friend's Wishlist", user_path(friend)%>)
        </li>
        <% end %>
      </ul>
    </div>
  <div class="col-lg-5 col-xs-12 showfriends">
    <h2>Users Who Have Befriended You</h2>
      <ul>
        <% current_user.inverse_friends do |user| %>
        <li><%=  user.name %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/home/_list_template.html.erb
<div class="header">
  <h1>Your Holiday Wishlist</h1>
</div>
<ul id="items-list" class="items-list">
  <%% items.each(function(item) { %>
    <li><a href="#items/<%%= item.get('image_url') %>"><%%= item.get('image_url') %></a></li>
  <%% }) %>
</ul>

app/views/home/index.html.erb
<div id="items-container" class="items-app">
  <form class="create_item">
    <input type="title" name="title" placeholder="Name of Item">
    <input type="image_url" name="image_url" placeholder="Image Url">
    <input type="url" name="url" placeholder="URL Link to Item">
    <button>Add Item</button>
</form>
</div>
<script type="template" id="items-list">
  <%= render 'list_template' %>
</script>

<script type="template" id="item-detail">
  <%= render 'detail_template' %>
</script>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= f.text_field :title, placeholder: "Item Title" %>
  <%= f.text_field :description, placeholder: "Description" %>
  <%= f.text_field :image_url, placeholder: "Image URL" %>
  <%= f.text_field :url, placeholder: "URL" %>
  Private?  <%= f.check_box :is_private %>
  <%= f.submit 'Add Item'%>
<% end %>

app/views/items/edit.html.erb
<div class=".col-md-6.col-md-offset-3" id="edit_page" >
<h1>Edit item</h1>
<%= render 'form' %>
<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>
</div>

app/views/items/friends_items.html.erb
<div id="items" class=“transitions-enabled”>
    <% @items.each do |item| %>
    <div class="box panel panel-default">
        <h2><%= image_tag item.image_url %></h2>
    <div class="panel-body">
      <h2><%= link_to item.title, item %></h2>
      <p class="user">Submitted by: <%= item.user.name %> </p>
    </div>
     <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% flash.each do |key, value| %>
<%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<% if current_user %>
<div id="items" class=“transitions-enabled”>
  <% @items.each do |item| %>
  <div class="box panel panel-default">
    <div class="image"><%= link_to image_tag(item.image_url), item %>
      <span class="title"><a href="<%= item.url %>" target=_blank><%= item.title %></a></span>
    </div>
  </div>
  <% end %>
</div>



<% else %>
<br>
<div class="row">
  <div class="container">
<div class="welcome_message">
<p>Welcome to Holiday Wishlist--We make secret santa easier than it has been ever before! You never have to be a vicitim of regifting ever again (or vise versa)! See what your friends really want for the holidays and share your wishlist with others. You can also add items from Etsy and save them into your wishlist.</p>
<br>
<p>More to come: You will soon be able to:
  <ol>
    <li>Purchase items with the We-Pay or Stripe </li>
    <li>Search for products from a collection of some of my favorite retailers (Jcrew, Anthropology, Nordstorm, etc..)</li>
    <li>See a single page view of all the products</li>
  </ol>
  </p>
</div>
</div>
</div>
<br>
<br>
<br>
<br>
<% end %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Add a new item</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div id="item_show" class="row">
  <div class="col-md-8 md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading item_image">
        <%= image_tag @item.image_url %>
      </div>
      <div class="panel-body">
        <h1><%= @item.title %></h1>
        <p class="description"><%= @item.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
            <div class="col-md-6">
                <p class="user">
                   Submitted by: <%= @item.user.name %>
                </p>
            </div>
            <div class="col-md-6">
                  <div class="btn-group pull-right">
                    <% if @item.user.name == current_user.name %>
                    <p class="btn btn-default"><%= link_to 'Edit', edit_item_path(@item) %></p>
                    <p class="btn btn-default"><%= link_to 'Back', items_path %></p>
                    <p class="btn btn-default"><%= link_to 'Delete', item_path, method: :delete, data: {confirm: "Are you sure?"} %></p>
                    <% end %>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HolidayWishlist</title>
  <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<body>
<div id="snowglobe">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="/items/">Holiday Wishlist</a>
      </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
         <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options <b class="caret"></b></a>
          <ul class="dropdown-menu">
           <% if user_signed_in? %>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <li><%= link_to 'New Item', new_item_path %> </li>
            <li><%= link_to "Search Items on Etsy", new_search_path %></li>
            <li><%= link_to 'My Items', root_path %></li>
            <li><%= link_to 'My Friends', friendship_path(current_user.id) %></li>
            <li> <%= link_to 'Add Friends', friendships_path %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>
          </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>
<br>
<br>
<br>
<br>
    <div class="row row-centered">
      <div id="site_banner" class="col-xs-6 col-centered">
        <%= image_tag("holiday_wishlist_banner.png")  %>
      </div>
    </div>
<br>
<br>
    <div class="container">
      <%= yield %>
    </div>
</div>
  </body>
</html>

app/views/searches/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-10 center">
        <h2> Products in the following category: <%= @category %></h2>
        <br>
        <table class="table table-striped table-bordered">
          <thead class="text-center">
            <th>Image</th>
           <th>Title</th>
            <th>Save to Wishlist </th>
          </thead>
          <tbody>
          <% @found_products.each do |products_hash| %>
            <% item_hash = {
              title: products_hash['title'],
              url: products_hash['url'],
              image_url: products_hash['MainImage']['url_170x135']
             }
            %>
            <tr>
              <td><% if products_hash['MainImage'] %><%= image_tag products_hash['MainImage']['url_170x135']  %><% end %></td>
              <td><%= link_to products_hash['title'], products_hash['url'], target: "_blank" %></td>
              <td><%= button_to('Save', items_path(item: item_hash), class: "btn btn-primary")%></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

<br>
<br>
<br>
<br>

app/views/searches/new.html.erb
<div class="row">
   <div class="col-md-6 col-centered">
  <h2>Browse Etsy Products</h2>
  <%= form_tag searches_path, method: :get do  %>
    <div class="field">
      <select name="name" id="category">
      <% @cat_list.each do |category| %>
        <option value= "<%= category['name'] %>"><%= category[
          'meta_title'] %></option>
          <% end %>
     </select>
    </div>
   <div class="actions">
     <%= submit_tag 'Search' %>
   </div>
  <% end %>
  </div>
  </div>

app/views/users/show.html.erb
<h3><%= @user.name%>'s Wishlist </h3>
<div id="items" class=“transitions-enabled”>
    <% @user.items.each do |item| %>
    <div class="box panel panel-default">
        <h2><%= image_tag item.image_url %></h2>
    <div class="panel-body">
      <h2><%= link_to item.title, item %></h2>
      <p class="user">Submitted by: <%= item.user.name %> </p>
    </div>
     <% end %>
  </div>
</div>